version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  labels:
  - kind/deps
  - ok-to-test
  commit-message:
    prefix: fix
    include: scope
- package-ecosystem: gomod
  directory: /tools
  schedule:
    interval: daily
  labels:
  - kind/deps
  - ok-to-test
  commit-message:
    prefix: fix
    include: scope
