exclude: |
  (?x)(
    (^vendor/)|
    (.deepcopy.go$)
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace

  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-mod-tidy
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: goimports
        name: goimports
        entry: hack/ensure-and-run-goimports.sh
        language: system
        types: [go]

      - id: golangci-lint
        name: golangci-lint
        entry: hack/ensure-and-run-golangci-lint.sh
        language: script
        pass_filenames: false
        types: [go]
