# permissions for end users to view addonimagesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addonimageset-viewer-role
rules:
- apiGroups:
  - addons.managed.openshift.io
  resources:
  - addonimagesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.managed.openshift.io
  resources:
  - addonimagesets/status
  verbs:
  - get
