# permissions for end users to view addontemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addontemplate-viewer-role
rules:
- apiGroups:
  - addonsflow.redhat.openshift.io
  resources:
  - addontemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addonsflow.redhat.openshift.io
  resources:
  - addontemplates/status
  verbs:
  - get
