# permissions for end users to edit addontemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addontemplate-editor-role
rules:
- apiGroups:
  - addonsflow.redhat.openshift.io
  resources:
  - addontemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addonsflow.redhat.openshift.io
  resources:
  - addontemplates/status
  verbs:
  - get
