
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - addonsflow.redhat.openshift.io
  resources:
  - AddonMetadata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addonsflow.redhat.openshift.io
  resources:
  - AddonMetadata/finalizers
  verbs:
  - update
- apiGroups:
  - addonsflow.redhat.openshift.io
  resources:
  - AddonMetadata/status
  verbs:
  - get
  - patch
  - update
